root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Build API entrypoint
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "./tmp/api"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "internal/database/migrations"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html", "sql"]
  log = "build-errors.log"

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = false
