// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"database/sql/driver"

	"github.com/gofrs/uuid/v5"
	enums "github.com/jacoobjake/einvoice-api/internal/database/enums"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type AuthToken runs hooks after queries
var _ bob.HookableType = &AuthToken{}

// Make sure the type FailedLogin runs hooks after queries
var _ bob.HookableType = &FailedLogin{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}

// Make sure the type enums.AuthTokenTypes satisfies database/sql.Scanner
var _ sql.Scanner = (*enums.AuthTokenTypes)(nil)

// Make sure the type enums.AuthTokenTypes satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(enums.AuthTokenTypes)

// Make sure the type uuid.UUID satisfies database/sql.Scanner
var _ sql.Scanner = (*uuid.UUID)(nil)

// Make sure the type uuid.UUID satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(uuid.UUID)

// Make sure the type pgtypes.Inet satisfies database/sql.Scanner
var _ sql.Scanner = (*pgtypes.Inet)(nil)

// Make sure the type pgtypes.Inet satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(pgtypes.Inet)

// Make sure the type enums.UserStatuses satisfies database/sql.Scanner
var _ sql.Scanner = (*enums.UserStatuses)(nil)

// Make sure the type enums.UserStatuses satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(enums.UserStatuses)
