// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var AuthTokenErrors = &authTokenErrors{
	ErrUniqueAuthTokensPkey: &UniqueConstraintError{
		schema:  "",
		table:   "auth_tokens",
		columns: []string{"id"},
		s:       "auth_tokens_pkey",
	},
}

type authTokenErrors struct {
	ErrUniqueAuthTokensPkey *UniqueConstraintError
}
