// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var FailedLoginErrors = &failedLoginErrors{
	ErrUniqueFailedLoginsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "failed_logins",
		columns: []string{"id"},
		s:       "failed_logins_pkey",
	},
}

type failedLoginErrors struct {
	ErrUniqueFailedLoginsPkey *UniqueConstraintError
}
